# Generated by Django 4.2 on 2023-04-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('profile_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/users/profile/')),
            ],
        ),
    ]
